### ISSUE TITLE
DRL-1.1 does not appear in the SPDX license list

### ISSUE THREAD

**Issue by kelnage** [SigmaHQ/Detection-Rule-License#2]
Previously, the DRL-1.0 was submitted to and accepted by the [SPDX](https://spdx.dev/) as a license (see [the submission](https://github.com/spdx/license-list-XML/issues/1075) and [the current license page](https://spdx.org/licenses/DRL-1.0.html)). Given the DRL has been updated to 1.1, I'd like to submit the new version of it to the SPDX; this would make it easier to associate it clearly with GitHub repositories (such as `SigmaHQ/sigma`) and may encourage wider uptake of it.

I'd be happy to act as the Steward for the submission, but I wanted to check that there were no issues with me doing so before I went ahead (particularly @Neo23x0, as the license author), and that weren't any forthcoming planned updates that might make this redundant?

**Comment by Neo23x0** [comment]
First of all, thank you for the heads-up and for taking the initiative. 

We've created this dedicated repository to be used as a reference. Previously, the licenses was hosted in the SigmaHQ/Sigma repository. All future references should point to this repo. 

I'd appreciate if you could do the submission for us. 

Thanks

**Comment by nasbench** [comment]
The PR has been merged and the license will be available at a later date :) https://github.com/spdx/license-list-XML/pull/2207

Thanks and closing this as resolved.
